const SCREEN_NAME = {
  // Universal
  UNIVERSAL_STACK: 'UniversalStack',
  UNIVERSAL_TAB: 'UniversalTab',
  UNIVERSAL_PRODUCTLIST: 'UniversalProductList',
  UINVERSAL_PRODUCTDETAIL: 'UniversalProductDetail',
  UNIVERSAL_HOME: 'Home',
  UNIVERSAL_HOME_SCREEN: 'UniversalHomeScreen',
  UNIVERSAL_KEY_INFO_SCREEN: 'UniversalKeyInfoScreen',
  WELCOME_SCREEN: 'WelcomeScreen',
  FLEX_TRADE: 'FlexiTrade',
  MY_ACCOUNT: 'Account',
  INSIGHTS: 'Insights',
  FEATURES: 'Features',
  EXPLORE: 'Explore',
  REFERRAL_LIST: 'ReferralList',

  UNIVERSAL_CATEGORY_SCREEN: 'UniversalCategoryScreen',
  APP_STACK: 'AppStack',
  WAREHOUSESCREEN: 'warehouseScreen',
  SPLASH_SCREEN: 'SplashScreen',
  UNIVERSALDRAWER: 'UniversalDrawer',
  VENDOR_DRAWER: 'VendorDrawer',
  VENDOR_INFO: 'vendorInfo',
  RETAILER_DRAWER: 'retailerDrawer',
  DRIVER_DRAWER: 'driverDrawer',
  LOGISTIC_PARTNER_DRAWER: 'logisticPartnerDrawer',
  CURRENT_ORDER: 'currentOrder',
  ORDER_DETAILS: 'orderDetails',
  COMING_SOON: 'comingSoonScreen',
  ORDERS_SCREEN: 'orders',
  PRODUCT_DETAILS_SCREEN: 'productDetails',
  // retailer
  RETAIL_PRICE_OFFER: 'RetailPriceOffer',
  NEW_ORDER: 'NewOrder',
  CUSTOMIZE_ORDER: 'CustomizeOrder',
  CONFIRM_ORDER: 'ConfirmOrder',
  RESTOCK_REFRESH_SCREEN: 'restockRefreshScreen',

  // multiple screen use profile
  PROFILE_SCREEN: 'ProfileScreen',
  UPDATE_PROFILE_SCREEN: 'UpdateProfileScreen',
  WAREHOUSE_SCREEN: 'warehouseScreen',
  COMPANY_DETAILS_SCREEN: 'companyDetailScreen',
  SETTING_SCREEN: 'settingScreen',
  SUPPORT_SCREEN: 'supportScreen',
  REVIEW_AND_FEEDBACK: 'reviewFeedbackScreen',
  RATING_FEEDBACK_SCREEN: 'RattingFeedbackScreen',
  CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreen',
  DELETE_ACCOUNT: 'DeleteAccountScreen',
  NOTIFICATION_SCREEN: 'NotificationScreen',
  TERMS_AND_CONDITION_SCREEN: 'termsAndConditionScreen',
  COMING_SOON_SCREEN: 'comingSoonScreen',
  INVENTORY_SYNC: 'inventorySync',
  PRIVACY_SECURITY_SCREEN: 'PrivacySecurityScreen',
  CATEGORY_PRODUCT_SCREEN: 'categoryProductScreen',
  NOTIFICATION_AND_ALERT_SCREEN: 'notificatationAndAlertScreen',
  FAQ_SCREEN: 'faqScreen',

  // auth
  AUTH_STACK: 'AuthStack',
  SIGNUP: 'signup',
  LOGIN: 'Login',
  OTP_SCREEN: 'otpscreen',
  FORGET: 'forget',
  ACCOUNT_VERIFICATION: 'accountVerification',
  SIGNUP_INFO_SCREEN: 'SignUpInfoScreen',
  SIGNUP_BUSSINESS_SCREEN: 'SignUpBusinessScreen',
  SIGNUP_DOCUMENT_SCREEN: 'SignUpDocumentScreen'
};

export default SCREEN_NAME;
